on:
  push:
     branches:
       - main
       
name: Ebook

jobs:
 
  bookdown:
    name: Ebook
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ~\AppData\Local\renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: | 
            ${{ runner.os }}-renv-
        
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      - name: Render Book
        run: Rscript -e 'bookdown::render_book()'
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book
  
# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@main
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
        name: _book 
        path: _book 
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@master
       env:
          EMAIL: ${{ secrets.EMAIL }}               # must be a verified email
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DIR: _book/
       with:
          build_dir: _book               # optional
          branch: gh-pages                # optional
